// src/components/fileReader/FileReader.vue
<template>
    <input type="file" id="inputFile" @change="onChange($event)">
    {{saveGame.player?.name}}
</template>

<script>
import { ref } from 'vue';

export default {
  setup() {
    const onChange = (event) => {
      fileUploaded(event)
    }

    let saveGame = ref({})

    function fileUploaded(event) {
    let file = event.target.files[0]
    let reader = new FileReader()
    reader.readAsText(file)

    reader.onload = () => {

        try {
            let xmlInfo = new DOMParser().parseFromString(reader.result, 'application/xml')
            let jsonInfo = xml2json(xmlInfo)
            
            saveGame.value.player = jsonInfo.SaveGame.player            
        } catch (e) {
            console.error("Error parsing XML:", e);
        }
	}
}

function xml2json(xml) {
  try {
    var obj = {};
    if (xml.children.length > 0) {
      for (var i = 0; i < xml.children.length; i++) {
        var item = xml.children.item(i);
        var nodeName = item.nodeName;

        if (typeof (obj[nodeName]) == "undefined") {
          obj[nodeName] = xml2json(item);
        } else {
          if (typeof (obj[nodeName].push) == "undefined") {
            var old = obj[nodeName];

            obj[nodeName] = [];
            obj[nodeName].push(old);
          }
          obj[nodeName].push(xml2json(item));
        }
      }
    } else {
      obj = xml.textContent;
    }
    return obj;
  } catch (e) {
      console.log(e.message);
  }
}

    return {
      onChange,
      saveGame,
    }
  }
}
</script>

// src/pages/file-reader/file-reader.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  templateUrl: './file-reader.component.html',
  styleUrl: './file-reader.component.scss',
})
export class FileReaderComponent {

  constructor(
    private router: Router,
  ) { }

  fileUploaded(event: any) {
    let file = event.target.files[0]
    let reader = new FileReader()
    reader.readAsText(file)

    reader.onload = () => {
      try {
        let xmlInfo = new DOMParser().parseFromString(reader.result as any, 'application/xml')
        let jsonInfo = this.xml2json(xmlInfo)
        console.log(jsonInfo.SaveGame);
      } catch (e) {
        console.error("Error parsing XML:", e);
      }
    }
  }

  xml2json(xml: any) {
    try {
      var obj: any = {};
      if (xml.children.length > 0) {
        for (var i = 0; i < xml.children.length; i++) {
          var item = xml.children.item(i);
          var nodeName = item.nodeName;

          if (typeof (obj[nodeName]) == "undefined") {
            obj[nodeName] = this.xml2json(item);
          } else {
            if (typeof (obj[nodeName].push) == "undefined") {
              var old = obj[nodeName];

              obj[nodeName] = [];
              obj[nodeName].push(old);
            }
            obj[nodeName].push(this.xml2json(item));
          }
        }
      } else {
        obj = xml.textContent;
      }
      return obj;
    } catch (e) {
      // console.log(e.message);
    }
  }
}

<main class="relative h-[70vh] w-full justify-center flex flex-col">
    <input class="opacity-0 absolute top-0 left-0 w-full h-[70vh] cursor-pointer" type="file"
        (change)="fileUploaded($event)">

    <img src="assets/logo.png" class="m-auto pixelated" alt="Stardew Valley Logo">

    <p class="text-center"><a href="%appdata%\StardewValley\Saves" target="_blank" rel="noopener noreferrer">%appdata%\StardewValley\Saves</a></p>
    <div class="m-auto text-center p-1 border-4 border-brown bg-lightbrown">
        <div class="bg-orange p-6">

            <p class="w-10 inline-block">
                <svg xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 640 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M144 480C64.5 480 0 415.5 0 336c0-62.8 40.2-116.2 96.2-135.9c-.1-2.7-.2-5.4-.2-8.1c0-88.4 71.6-160 160-160c59.3 0 111 32.2 138.7 80.2C409.9 102 428.3 96 448 96c53 0 96 43 96 96c0 12.2-2.3 23.8-6.4 34.6C596 238.4 640 290.1 640 352c0 70.7-57.3 128-128 128H144zm79-217c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l39-39V392c0 13.3 10.7 24 24 24s24-10.7 24-24V257.9l39 39c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-80-80c-9.4-9.4-24.6-9.4-33.9 0l-80 80z" />
                </svg>
            </p>

            <p>Drag & drop your farm file here</p>
            <p> or <strong>browse file</strong> from device</p>
        </div>
    </div>

</main>
